version: "3.8"

services:
  db:
    image: postgres:14 # Using postgres:14 as per your current config
    restart: always
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"

  pgadmin: # New service for pgAdmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com # Replace with your desired email
      PGADMIN_DEFAULT_PASSWORD: admin_password # Replace with your desired password
      PGADMIN_LISTEN_PORT: 80 # pgAdmin's internal port
    ports:
      - "8080:80" # Map host port 8080 to container's port 80 (pgAdmin's default web port)
    depends_on:
      - db # Ensure pgAdmin starts after the database is up
    volumes:
      - pgadmin_data:/var/lib/pgadmin # Persist pgAdmin configuration and data

volumes:
  pgdata:
  pgadmin_data: # New volume for pgAdmin data
